-- 001_sd03_baseline.sql
-- 원본: design/gugak_ddl.sql (SD_03, 2026-09-28 14:58, 박예은 팀장) — 본문은 바꾸지 않았다.
-- 머리에 문자셋 지정만 더했다(JSG_DB설계검증 V-1: 팀 DB 기본이 latin1이면 한글이 깨진다).
SET NAMES utf8mb4;
ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- =====================================================================
-- 국악보 디지털 변환·연주·편집 서비스 (1단계) — 데이터베이스 DDL
-- 설계서: design/SD_03_데이터베이스설계서_국악보변환서비스.md
-- 작성: 박예은(팀장) 세션 · 2026-09-28
--
-- 작성 규약
--   * 표준 SQL 을 기본으로 한다. 검증 DBMS 는 MariaDB 12.0.2 이다.
--   * DBMS 전용 구문은 쓰는 자리에 [MariaDB] 주석으로 이유를 남긴다.
--     공통으로 쓰는 것은 여기에 한 번만 적는다.
--       [MariaDB] AUTO_INCREMENT      — 표준 GENERATED BY DEFAULT AS IDENTITY 를 MariaDB 가 지원하지 않는다.
--       [MariaDB] TIMESTAMPDIFF()     — 표준 (a - b) 기간 연산을 MariaDB 가 지원하지 않는다.
--       [MariaDB] CREATE OR REPLACE VIEW / TRIGGER — 멱등 실행용. 표준에는 OR REPLACE 가 없다.
--       [MariaDB] CREATE INDEX IF NOT EXISTS       — 멱등 실행용. 표준에는 IF NOT EXISTS 가 없다.
--       [MariaDB] DELIMITER           — mariadb 클라이언트 지시어(트리거 본문의 ; 처리). SQL 문이 아니다.
--       [MariaDB] 트리거 본문의 IF/SIGNAL — SQL/PSM(표준 9075-4) 형식이다. 제품마다 문법 차이가 있다.
--   * 생성 순서는 FK 의존 위상 순서다(참조되는 테이블이 먼저).
--   * 재실행해도 실패하지 않는다(IF NOT EXISTS · OR REPLACE · NOT EXISTS 가드).
--   * 업무규칙 구현 제약에는 어느 BR/게이트의 구현인지 주석을 단다.
--   * 원천에 값이 없는 임계값·기간은 지어내지 않는다. 컬럼은 두고 NULL(미정)을 허용한다.
--     원천에 값이 있는 상수(24시간, 7일, 20MB, 800px, .sf2 50MB, 세션당 3개)만 제약·뷰에 넣는다.
--
-- 논리 설계와 달라진 점(실행 중 이탈 기록)
--   D1. 설정 변경 이력 뷰(v_setting_change_history)의 엔진 순서 비교에 GROUP_CONCAT 을 썼다.
--       표준은 LISTAGG 이나 MariaDB 가 지원하지 않는다.
--   D3. 검증 중 발견: "col IN (...)" 조건은 col 이 NULL 이면 UNKNOWN 이 되어 CHECK 를 통과한다.
--       이미지인데 종류 없음 · 이유 없는 대체 · 종류 없는 진짜 평가 악보가 받아들여졌다. IS NOT NULL 을 더해 막았다.
--   D2. 트리거는 뷰를 읽어 판정한다(G4 는 v_request_retention). 판정식을 트리거에 다시 쓰지 않기 위해서다.
--       그래서 뷰를 테이블 뒤, 트리거 앞에 만든다.
-- =====================================================================


-- =====================================================================
-- 영역 F. 운영 (쓰기 주체: 운영자 · 생애: 영구)  — 다른 영역이 참조하므로 먼저 만든다
-- =====================================================================

-- F1 운영자 계정 (FR-051 · Key Entities 운영자 계정)
CREATE TABLE IF NOT EXISTS operator_account (
  operator_id     BIGINT        NOT NULL AUTO_INCREMENT,
  login_id        VARCHAR(64)   NOT NULL,
  password_hash   VARCHAR(255)  NOT NULL,          -- 복원 불가 형태(해시 방식 미정)
  display_name    VARCHAR(100)  NOT NULL,
  created_at      TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  disabled_at     TIMESTAMP(3)  NULL,
  CONSTRAINT pk_operator_account PRIMARY KEY (operator_id),
  CONSTRAINT uq_operator_login UNIQUE (login_id),
  -- BR-OPS-07: 개인 운영자 계정만(빈 아이디·빈 해시 금지)
  CONSTRAINT chk_operator_nonempty CHECK (TRIM(login_id) <> '' AND TRIM(password_hash) <> '')
);

-- F2 처리 설정 판본 (H5 · UC10 · BR-OPS-02·06·09)
--   한 판본 = 저장 버튼 한 번. 요청은 접수 시점의 판본을 참조한다(BR-OPS-02 "이후 요청부터").
CREATE TABLE IF NOT EXISTS processing_setting_version (
  setting_version_id          BIGINT        NOT NULL AUTO_INCREMENT,
  created_at                  TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_by                  BIGINT        NOT NULL,
  timeout_seconds             INT           NULL,   -- 처리 시간 제한(값 미정)
  max_concurrency             INT           NULL,   -- 동시 처리 상한(값 미정)
  fallback_enabled            BOOLEAN       NOT NULL DEFAULT TRUE,  -- 끌 수 있게 할지 미정(미해결 #1)
  default_call_limit_per_day  INT           NULL,   -- 새 키 기본 호출 한도(값 미정)
  apply_rate_limit_count      INT           NULL,   -- 신청 빈도 제한: 창 안 허용 건수(값 미정)
  apply_rate_window_minutes   INT           NULL,   -- 신청 빈도 제한: 창 길이(값 미정)
  structure_threshold         DECIMAL(5,4)  NULL,   -- 구조 확인 기준값(값 미정, 척도 [추론] 0~1)
  grade_caution_boundary      DECIMAL(5,4)  NULL,   -- 이 값 미만이면 주의(값 미정)
  grade_distrust_boundary     DECIMAL(5,4)  NULL,   -- 이 값 미만이면 불신(값 미정)
  api_apply_status            VARCHAR(12)   NOT NULL DEFAULT 'pending',
  api_applied_at              TIMESTAMP(3)  NULL,
  CONSTRAINT pk_setting_version PRIMARY KEY (setting_version_id),
  CONSTRAINT fk_setting_operator FOREIGN KEY (created_by) REFERENCES operator_account (operator_id),
  -- G6 운영 값 검증 (UC10 E2 · UC14 E1 [추론] "0·음수 금지")
  CONSTRAINT chk_g6_timeout      CHECK (timeout_seconds > 0),
  CONSTRAINT chk_g6_concurrency  CHECK (max_concurrency >= 1),
  CONSTRAINT chk_g6_default_limit CHECK (default_call_limit_per_day >= 1),
  CONSTRAINT chk_g6_rate_count   CHECK (apply_rate_limit_count >= 1),
  -- G6 + BR-KEY-06: 신청 내용은 7일 뒤 지워지므로 7일(10080분)보다 긴 창은 판정할 자료가 없다
  CONSTRAINT chk_g6_rate_window  CHECK (apply_rate_window_minutes BETWEEN 1 AND 10080),
  CONSTRAINT chk_g6_structure    CHECK (structure_threshold BETWEEN 0 AND 1),
  -- G6 (UC10 E8 [추론]): 주의 경계가 불신 경계보다 엄격해야 한다(불신 < 주의)
  CONSTRAINT chk_g6_grade_range  CHECK (grade_caution_boundary BETWEEN 0 AND 1
                                        AND grade_distrust_boundary BETWEEN 0 AND 1),
  CONSTRAINT chk_g6_grade_order  CHECK (grade_distrust_boundary < grade_caution_boundary),
  -- UC10 E5: 반영 상태는 셋 중 하나, 반영됨이면 반영 시각이 있다
  CONSTRAINT chk_setting_apply   CHECK (api_apply_status IN ('pending','applied','unapplied')),
  CONSTRAINT chk_setting_applied_at CHECK ((api_apply_status = 'applied' AND api_applied_at IS NOT NULL)
                                        OR (api_apply_status <> 'applied' AND api_applied_at IS NULL))
);

-- F3 엔진 호출 순서 (BR-ENG-02 · BR-OPS-06 오선보·정간보 각각)
CREATE TABLE IF NOT EXISTS setting_engine_order (
  setting_version_id  BIGINT       NOT NULL,
  score_type          VARCHAR(12)  NOT NULL,
  seq                 SMALLINT     NOT NULL,
  engine_name         VARCHAR(40)  NOT NULL,
  CONSTRAINT pk_setting_engine_order PRIMARY KEY (setting_version_id, score_type, seq),
  CONSTRAINT uq_setting_engine_once UNIQUE (setting_version_id, score_type, engine_name),
  CONSTRAINT fk_engine_order_version FOREIGN KEY (setting_version_id)
    REFERENCES processing_setting_version (setting_version_id) ON DELETE CASCADE,
  CONSTRAINT chk_engine_order_type CHECK (score_type IN ('staff','jeongganbo')),
  CONSTRAINT chk_engine_order_seq  CHECK (seq >= 1)
);

-- F4 라이선스 정책 (G7 · BR-RND-03·06 · SD_01 §11-2 "라이선스 확인 여부 플래그")
CREATE TABLE IF NOT EXISTS license_policy (
  policy_code   VARCHAR(40)   NOT NULL,
  confirmed     BOOLEAN       NOT NULL DEFAULT FALSE,
  decided_by    BIGINT        NULL,
  decided_at    TIMESTAMP(3)  NULL,
  CONSTRAINT pk_license_policy PRIMARY KEY (policy_code),
  CONSTRAINT fk_license_operator FOREIGN KEY (decided_by) REFERENCES operator_account (operator_id),
  CONSTRAINT chk_license_code CHECK (policy_code IN ('sound_and_renderer')),
  -- G7 해제 기록: 확인됨으로 바꾼 사람과 시각이 있어야 한다
  CONSTRAINT chk_license_decided CHECK (confirmed = FALSE OR (decided_by IS NOT NULL AND decided_at IS NOT NULL))
);

-- 원천 사실: 라이선스는 아직 확인되지 않았다(BR-RND-03·06). 행이 없을 때만 넣는다(멱등).
INSERT INTO license_policy (policy_code, confirmed)
SELECT 'sound_and_renderer', FALSE FROM (SELECT 1 AS one) AS seed
 WHERE NOT EXISTS (SELECT 1 FROM license_policy WHERE policy_code = 'sound_and_renderer');


-- =====================================================================
-- 영역 D-카탈로그. 악기와 악기 구성 (쓰기 주체: 계획 단계 등록 · 추천 모델 · API 선택 항목 · 생애: 영구)
-- =====================================================================

-- D1 악기 (BR-PLY-03 국악기 먼저 · FR-023 · C4)
CREATE TABLE IF NOT EXISTS instrument (
  instrument_id   BIGINT       NOT NULL AUTO_INCREMENT,
  name            VARCHAR(60)  NOT NULL,     -- MusicXML 에 글자로 적는 이름(BR-EDT-06)
  family          VARCHAR(10)  NOT NULL,
  midi_program    SMALLINT     NULL,         -- 국악기 표기 방법 미정(UC_00 미해결 18)
  range_low       SMALLINT     NULL,         -- 연주 가능 음역 아래(MIDI 음번호, 값 미정) — S2 음역 경고(BR-EDT-03)
  range_high      SMALLINT     NULL,         -- 연주 가능 음역 위(값 미정)
  is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
  CONSTRAINT pk_instrument PRIMARY KEY (instrument_id),
  CONSTRAINT uq_instrument_name UNIQUE (name),
  CONSTRAINT chk_instrument_family CHECK (family IN ('gugak','other')),
  CONSTRAINT chk_instrument_program CHECK (midi_program BETWEEN 0 AND 127),
  CONSTRAINT chk_instrument_range CHECK (range_low BETWEEN 0 AND 127 AND range_high BETWEEN 0 AND 127
                                      AND range_low <= range_high)
);

-- D2 악기 구성 (기본 국악기 구성 · 추천 조합 · 원래 악기 · API 직접 지정)
CREATE TABLE IF NOT EXISTS ensemble (
  ensemble_id     BIGINT       NOT NULL AUTO_INCREMENT,
  ensemble_kind   VARCHAR(12)  NOT NULL,
  created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  -- BR-PLY-01: 기본 국악기 구성은 하나뿐이다. default 행에만 1, 나머지는 NULL 이 되어 UNIQUE 가 하나만 허용한다.
  default_marker  SMALLINT GENERATED ALWAYS AS (CASE WHEN ensemble_kind = 'default' THEN 1 ELSE NULL END) STORED,
  CONSTRAINT pk_ensemble PRIMARY KEY (ensemble_id),
  CONSTRAINT uq_ensemble_single_default UNIQUE (default_marker),
  CONSTRAINT chk_ensemble_kind CHECK (ensemble_kind IN ('default','recommended','original','custom'))
);

-- D3 악기 구성의 파트
CREATE TABLE IF NOT EXISTS ensemble_member (
  ensemble_id               BIGINT        NOT NULL,
  part_no                   SMALLINT      NOT NULL,
  part_role                 VARCHAR(12)   NULL,   -- 선율·타악(예: "선율 가야금·타악 장구")
  instrument_id             BIGINT        NULL,
  original_instrument_name  VARCHAR(100)  NULL,   -- 올린 MIDI·MusicXML 에 적힌 악기(BR-PLY-04)
  original_midi_program     SMALLINT      NULL,
  CONSTRAINT pk_ensemble_member PRIMARY KEY (ensemble_id, part_no),
  CONSTRAINT fk_member_ensemble FOREIGN KEY (ensemble_id) REFERENCES ensemble (ensemble_id) ON DELETE CASCADE,
  CONSTRAINT fk_member_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (instrument_id),
  CONSTRAINT chk_member_part CHECK (part_no >= 1),
  CONSTRAINT chk_member_role CHECK (part_role IN ('melody','percussion','other')),
  -- 서비스 악기이거나 원래 악기이거나 둘 중 하나
  CONSTRAINT chk_member_one_source CHECK ((instrument_id IS NOT NULL AND original_instrument_name IS NULL)
                                       OR (instrument_id IS NULL AND original_instrument_name IS NOT NULL)),
  CONSTRAINT chk_member_program CHECK (original_midi_program BETWEEN 0 AND 127)
);


-- =====================================================================
-- 영역 C-템플릿. 대체 템플릿 (쓰기 주체: 계획 단계 등록 · 생애: 영구)
-- =====================================================================

-- C1 대체 템플릿 (Key Entities · BR-FBK-02·06 · UC12 사전조건 ③)
CREATE TABLE IF NOT EXISTS fallback_template (
  template_id   BIGINT        NOT NULL AUTO_INCREMENT,
  holder        VARCHAR(12)   NOT NULL,   -- web: 웹 서비스 보유 / api_server: 모델 API 서버 보유
  name          VARCHAR(100)  NOT NULL,
  midi_uri      VARCHAR(500)  NOT NULL,
  is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_fallback_template PRIMARY KEY (template_id),
  CONSTRAINT uq_fallback_template UNIQUE (holder, name),
  CONSTRAINT chk_template_holder CHECK (holder IN ('web','api_server'))
);


-- =====================================================================
-- 영역 E. API 접근 키·호출 (쓰기 주체: 웹 서비스(신청)·운영자(폐기·한도)·모델 API 서버(호출 기록))
--         생애: 키는 영구, 신청 내용은 7일(보관 처리 시 계속)
-- =====================================================================

-- E1 접근 키 (H6 · BR-KEY-01~05 · FR-053·055) — 키 원문 컬럼은 두지 않는다(BR-KEY-05 · G9)
CREATE TABLE IF NOT EXISTS access_key (
  key_id              BIGINT        NOT NULL AUTO_INCREMENT,
  key_kind            VARCHAR(10)   NOT NULL,
  key_hash            VARCHAR(255)  NOT NULL,   -- 해시 방식 미정
  key_prefix          VARCHAR(16)   NOT NULL,   -- 앞 몇 글자(글자 수 미정)
  application_no      VARCHAR(20)   NULL,       -- 외부 키의 신청 번호. 신청 내용이 지워져도 남는다
  call_limit_per_day  INT           NULL,
  issued_at           TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  issued_by           BIGINT        NULL,       -- 서비스 전용 키만 운영자가 발급(UC14 A2)
  status              VARCHAR(8)    NOT NULL DEFAULT 'active',
  revoked_at          TIMESTAMP(3)  NULL,
  revoked_by          BIGINT        NULL,
  CONSTRAINT pk_access_key PRIMARY KEY (key_id),
  CONSTRAINT uq_access_key_hash UNIQUE (key_hash),
  CONSTRAINT uq_access_key_application UNIQUE (application_no),
  CONSTRAINT fk_key_issued_by FOREIGN KEY (issued_by) REFERENCES operator_account (operator_id),
  CONSTRAINT fk_key_revoked_by FOREIGN KEY (revoked_by) REFERENCES operator_account (operator_id),
  CONSTRAINT chk_key_kind CHECK (key_kind IN ('external','service')),
  -- BR-KEY-01: 외부 키는 신청으로 자동 발급(운영자 없음), 서비스 전용 키는 신청 없이 운영자가 발급
  CONSTRAINT chk_key_origin CHECK ((key_kind = 'external' AND application_no IS NOT NULL AND issued_by IS NULL)
                                OR (key_kind = 'service'  AND application_no IS NULL AND issued_by IS NOT NULL)),
  -- BR-KEY-03 · G6: 외부 키는 한도가 반드시 있고 1 이상. 서비스 전용 키의 한도 적용 여부는 미정(미해결)
  CONSTRAINT chk_key_limit CHECK (call_limit_per_day >= 1),
  CONSTRAINT chk_key_limit_required CHECK (key_kind = 'service' OR call_limit_per_day IS NOT NULL),
  -- BR-KEY-02: 상태 머신 — 사용 중이면 폐기 정보가 없고, 폐기면 시각과 처리 운영자가 있다
  CONSTRAINT chk_key_status CHECK ((status = 'active'  AND revoked_at IS NULL AND revoked_by IS NULL)
                                OR (status = 'revoked' AND revoked_at IS NOT NULL AND revoked_by IS NOT NULL))
);

-- E2 접근 키 신청 내용 (H7 · BR-KEY-06·07 · FR-060·061) — 키 기록과 따로 두고 7일 뒤 행을 지운다
CREATE TABLE IF NOT EXISTS key_application (
  key_id           BIGINT         NOT NULL,
  applicant_name   VARCHAR(100)   NOT NULL,
  affiliation      VARCHAR(200)   NOT NULL,
  contact_email    VARCHAR(254)   NOT NULL,
  purpose          VARCHAR(1000)  NOT NULL,
  applied_at       TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  consent_given    BOOLEAN        NOT NULL,
  client_address   VARCHAR(45)    NOT NULL,   -- G11 "같은 접속 주소" 판정용. 신청 내용과 함께 지워진다
  retained_at      TIMESTAMP(3)   NULL,       -- 보관 처리(7일 자동 삭제에서 뺌)
  retained_by      BIGINT         NULL,
  CONSTRAINT pk_key_application PRIMARY KEY (key_id),
  CONSTRAINT fk_application_key FOREIGN KEY (key_id) REFERENCES access_key (key_id),
  CONSTRAINT fk_application_retained_by FOREIGN KEY (retained_by) REFERENCES operator_account (operator_id),
  -- G10 신청 필수 항목(UC15 E1): 네 항목이 비어 있지 않다
  CONSTRAINT chk_g10_required CHECK (TRIM(applicant_name) <> '' AND TRIM(affiliation) <> ''
                                  AND TRIM(contact_email) <> '' AND TRIM(purpose) <> ''),
  -- G10 + BR-KEY-07: 개인정보 수집·이용 동의 없이는 저장하지 않는다
  CONSTRAINT chk_g10_consent CHECK (consent_given = TRUE),
  -- BR-KEY-06: 보관 처리는 시각과 처리 운영자가 함께 있다
  CONSTRAINT chk_application_retained CHECK ((retained_at IS NULL AND retained_by IS NULL)
                                          OR (retained_at IS NOT NULL AND retained_by IS NOT NULL))
);


-- =====================================================================
-- 영역 A. 접수·요청 (쓰기 주체: 웹 서비스(웹 요청) · 모델 API 서버(API 요청) · 생애: 요청 행은 영구, 파일은 24시간)
-- =====================================================================

-- A1 익명 세션 (spec Assumptions 사용자와 접근 · UC8 세션 단위)
CREATE TABLE IF NOT EXISTS anon_session (
  session_id      CHAR(36)      NOT NULL,     -- 앱이 만든 무작위 식별자
  started_at      TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_active_at  TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ended_at        TIMESTAMP(3)  NULL,         -- 세션 종료 판정 기준은 미정(UC8 E4)
  CONSTRAINT pk_anon_session PRIMARY KEY (session_id),
  CONSTRAINT chk_session_time CHECK (ended_at IS NULL OR ended_at >= started_at)
);

-- A2 악보 요청 (Key Entities 악보 요청 · H1·H4 · UC3 사후조건 ①)
CREATE TABLE IF NOT EXISTS score_request (
  request_id          BIGINT        NOT NULL AUTO_INCREMENT,
  request_no          VARCHAR(20)   NOT NULL,   -- 화면·API 요청 번호(예: R-0928-0012). 발급 뒤 바뀌지 않는다
  channel             VARCHAR(4)    NOT NULL,   -- 요청 경로
  session_id          CHAR(36)      NULL,
  access_key_id       BIGINT        NULL,
  file_kind           VARCHAR(10)   NOT NULL,
  chosen_score_type   VARCHAR(12)   NULL,       -- 사용자가 고른 악보 종류(이미지일 때)
  route               VARCHAR(10)   NOT NULL,   -- 적용 경로
  fallback_reason     VARCHAR(20)   NULL,
  status              VARCHAR(22)   NOT NULL DEFAULT 'received',
  setting_version_id  BIGINT        NOT NULL,   -- 접수 시점 설정(BR-OPS-02)
  received_at         TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  completed_at        TIMESTAMP(3)  NULL,
  result_shown_at     TIMESTAMP(3)  NULL,       -- 웹: 결과 악보가 처음 보인 시각(BR-OPS-04 기다린 시간)
  first_played_at     TIMESTAMP(3)  NULL,       -- 웹: 처음 소리가 난 시각(BR-OPS-04)
  purged_at           TIMESTAMP(3)  NULL,       -- P0 가 원본·결과물을 지운 시각
  CONSTRAINT pk_score_request PRIMARY KEY (request_id),
  CONSTRAINT uq_request_no UNIQUE (request_no),
  CONSTRAINT fk_request_session FOREIGN KEY (session_id) REFERENCES anon_session (session_id),
  CONSTRAINT fk_request_key FOREIGN KEY (access_key_id) REFERENCES access_key (key_id),
  CONSTRAINT fk_request_setting FOREIGN KEY (setting_version_id)
    REFERENCES processing_setting_version (setting_version_id),
  CONSTRAINT chk_request_channel CHECK (channel IN ('web','api')),
  -- 웹 요청은 익명 세션, API 요청은 접근 키에 묶인다(BR-API-03 · UC13 E7 소유 확인 근거)
  CONSTRAINT chk_request_owner CHECK ((channel = 'web' AND session_id IS NOT NULL AND access_key_id IS NULL)
                                   OR (channel = 'api' AND session_id IS NULL AND access_key_id IS NOT NULL)),
  -- BR-UPL-01: 이미지·MIDI·MusicXML 만
  CONSTRAINT chk_request_file_kind CHECK (file_kind IN ('image','midi','musicxml')),
  -- BR-ENG-05: 이미지면 종류를 반드시 고르고, MIDI·MusicXML 은 고르지 않는다
  --   주의: NULL 이 IN (...) 을 만나면 UNKNOWN 이 되어 CHECK 를 통과한다. 그래서 IS NOT NULL 을 함께 건다(검증 중 발견)
  CONSTRAINT chk_request_score_type CHECK ((file_kind = 'image' AND chosen_score_type IS NOT NULL
                                            AND chosen_score_type IN ('staff','jeongganbo'))
                                        OR (file_kind <> 'image' AND chosen_score_type IS NULL)),
  -- BR-RTE-01·03: 이미지는 인식 변환 또는 대체, MIDI·MusicXML 은 직행
  CONSTRAINT chk_request_route CHECK ((file_kind = 'image' AND route IN ('recognize','fallback'))
                                   OR (file_kind <> 'image' AND route = 'direct')),
  -- BR-FBK-03 · BR-RTE-02: 대체면 이유가 있고, 대체가 아니면 이유가 없다. 이유 6가지
  CONSTRAINT chk_request_fallback CHECK ((route = 'fallback' AND fallback_reason IS NOT NULL AND fallback_reason IN
                                          ('recognition_failed','timeout','engine_stopped',
                                           'user_request','no_structure','distrust'))
                                      OR (route <> 'fallback' AND fallback_reason IS NULL)),
  CONSTRAINT chk_request_status CHECK (status IN ('received','queued','converting','awaiting_type_answer',
                                                  'rendering','completed','service_down')),
  -- BR-ENG-07: 종류 확인 질문은 웹에서만 한다
  CONSTRAINT chk_request_ask_web_only CHECK (status <> 'awaiting_type_answer' OR channel = 'web'),
  -- UC13 6단계: "연주 생성" 단계는 API 연주 요청에만 있다
  CONSTRAINT chk_request_render_api_only CHECK (status <> 'rendering' OR channel = 'api'),
  -- UC1 E7 · UC2 E1: 서비스 중단은 대체 템플릿마저 못 불러온 경우뿐이다
  CONSTRAINT chk_request_service_down CHECK (status <> 'service_down' OR route = 'fallback'),
  -- BR-FBK-04: 완료 상태와 완료 시각은 함께 있다
  CONSTRAINT chk_request_completed CHECK ((status = 'completed' AND completed_at IS NOT NULL)
                                       OR (status <> 'completed' AND completed_at IS NULL)),
  -- 화면 표시·재생 시각은 웹 요청에만 있다
  CONSTRAINT chk_request_web_times CHECK (channel = 'web' OR (result_shown_at IS NULL AND first_played_at IS NULL))
);

-- A3 업로드 원본 (BR-UPL-02·03 · BR-RET-01)
CREATE TABLE IF NOT EXISTS upload_file (
  upload_id            BIGINT        NOT NULL AUTO_INCREMENT,
  request_id           BIGINT        NOT NULL,
  original_name        VARCHAR(255)  NOT NULL,
  size_bytes           BIGINT        NOT NULL,
  image_short_side_px  INT           NULL,       -- 이미지일 때만
  storage_uri          VARCHAR(500)  NULL,
  stored_at            TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at           TIMESTAMP(3)  NULL,
  CONSTRAINT pk_upload_file PRIMARY KEY (upload_id),
  -- BR-UPL-02: 요청 하나에 파일 하나
  CONSTRAINT uq_upload_one_per_request UNIQUE (request_id),
  CONSTRAINT fk_upload_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT chk_upload_size CHECK (size_bytes > 0),
  -- G1 마지막 방어선(BR-UPL-03 시작값): 이미지는 짧은 변 800px 이상 · 20MB(20971520 바이트) 이하.
  --   값을 조정하면 이 제약을 교체한다. MIDI·MusicXML 용량 상한은 미정이라 제약이 없다.
  CONSTRAINT chk_g1_image_limits CHECK (image_short_side_px IS NULL
                                     OR (image_short_side_px >= 800 AND size_bytes <= 20971520)),
  -- BR-RET-01: 지웠으면 위치가 없고, 안 지웠으면 위치가 있다
  CONSTRAINT chk_upload_deleted CHECK ((deleted_at IS NULL AND storage_uri IS NOT NULL)
                                    OR (deleted_at IS NOT NULL AND storage_uri IS NULL))
);

-- A4 연주 요청 선택 항목 (UC13 · BR-API-08 · BR-PLY-04)
CREATE TABLE IF NOT EXISTS performance_option (
  request_id           BIGINT       NOT NULL,
  instrument_mode      VARCHAR(10)  NOT NULL DEFAULT 'default',
  ensemble_id          BIGINT       NULL,     -- 직접 지정한 악기 구성
  transpose_semitones  SMALLINT     NOT NULL DEFAULT 0,
  volume_level         SMALLINT     NULL,     -- 음량 척도 미정
  CONSTRAINT pk_performance_option PRIMARY KEY (request_id),
  CONSTRAINT fk_perf_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT fk_perf_ensemble FOREIGN KEY (ensemble_id) REFERENCES ensemble (ensemble_id),
  -- BR-API-08: 직접 지정 · 추천 · 원래 악기 · 넣지 않음(기본 국악기 구성)
  CONSTRAINT chk_perf_mode CHECK (instrument_mode IN ('default','explicit','recommend','original')),
  CONSTRAINT chk_perf_explicit CHECK ((instrument_mode = 'explicit' AND ensemble_id IS NOT NULL)
                                   OR (instrument_mode <> 'explicit' AND ensemble_id IS NULL)),
  CONSTRAINT chk_perf_volume CHECK (volume_level >= 0)
);


-- =====================================================================
-- 영역 E (계속). API 호출 기록 — 요청을 참조하므로 A 뒤에 만든다
-- =====================================================================

-- E3 API 호출 기록 (G2·G3 판정 근거 · 5.11 "호출 횟수를 한도 계산에 반영")
CREATE TABLE IF NOT EXISTS api_call_log (
  call_id          BIGINT        NOT NULL AUTO_INCREMENT,
  called_at        TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  endpoint         VARCHAR(100)  NOT NULL,   -- 예: POST /v1/omr/staff
  access_key_id    BIGINT        NULL,       -- 키가 없거나 알 수 없는 키면 NULL
  outcome          VARCHAR(22)   NOT NULL,
  reason_code      VARCHAR(40)   NULL,
  retry_after_at   TIMESTAMP(3)  NULL,
  request_id       BIGINT        NULL,
  CONSTRAINT pk_api_call_log PRIMARY KEY (call_id),
  CONSTRAINT fk_call_key FOREIGN KEY (access_key_id) REFERENCES access_key (key_id),
  CONSTRAINT fk_call_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT chk_call_outcome CHECK (outcome IN ('accepted','rejected_key','rejected_limit',
                                                 'rejected_concurrency','rejected_file','expired','not_found')),
  -- G2: 받아들인 호출은 반드시 유효 키로 식별된다
  CONSTRAINT chk_call_accepted_key CHECK (outcome <> 'accepted' OR access_key_id IS NOT NULL),
  -- BR-API-05: 거절에는 사유 코드가 있다
  CONSTRAINT chk_call_reason CHECK ((outcome = 'accepted' AND reason_code IS NULL)
                                 OR (outcome <> 'accepted' AND reason_code IS NOT NULL)),
  -- BR-API-04 · G3: 한도 초과 거절에는 다시 시도할 시점이 있다
  CONSTRAINT chk_call_retry CHECK ((outcome IN ('rejected_limit','rejected_concurrency') AND retry_after_at IS NOT NULL)
                                OR (outcome NOT IN ('rejected_limit','rejected_concurrency') AND retry_after_at IS NULL)),
  -- G1: 파일 반려는 요청을 만들지 않는다
  CONSTRAINT chk_call_no_request_on_reject CHECK (outcome NOT IN ('rejected_key','rejected_limit',
                                                  'rejected_concurrency','rejected_file') OR request_id IS NULL)
);


-- =====================================================================
-- 영역 B. 인식 판정 (쓰기 주체: 모델 API 서버 · 생애: 요청 기록과 같이 영구)
-- =====================================================================

-- B1 인식 작업 (Key Entities 작업 · H9 · 1.7~1.12 · 5.5)
CREATE TABLE IF NOT EXISTS processing_job (
  request_id            BIGINT        NOT NULL,
  confirmed_score_type  VARCHAR(12)   NOT NULL,   -- 종류 확인 뒤 확정 종류
  structure_verdict     VARCHAR(10)   NOT NULL,
  type_mismatch         BOOLEAN       NOT NULL DEFAULT FALSE,
  type_answer           VARCHAR(8)    NULL,       -- 웹에서 물었을 때의 답
  validity_grade        VARCHAR(10)   NULL,       -- 판정 시점의 경계로 매긴 등급(저장하는 유도값)
  started_at            TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  finished_at           TIMESTAMP(3)  NULL,
  CONSTRAINT pk_processing_job PRIMARY KEY (request_id),
  CONSTRAINT fk_job_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT chk_job_type CHECK (confirmed_score_type IN ('staff','jeongganbo')),
  -- BR-ENG-06: 통과 · 애매 · 불통과
  CONSTRAINT chk_job_structure CHECK (structure_verdict IN ('pass','ambiguous','fail')),
  -- BR-FBK-07: 신뢰 · 주의 · 불신
  CONSTRAINT chk_job_grade CHECK (validity_grade IN ('trust','caution','distrust')),
  -- BR-ENG-06: 구조 불통과면 엔진을 부르지 않으므로 등급이 없다
  CONSTRAINT chk_job_no_grade_on_fail CHECK (structure_verdict <> 'fail' OR validity_grade IS NULL),
  -- BR-ENG-07: 답은 불일치가 있을 때만 있다
  CONSTRAINT chk_job_answer CHECK (type_answer IS NULL OR (type_mismatch = TRUE AND type_answer IN ('changed','kept')))
);

-- B2 엔진 시도 (1.9 · BR-ENG-02 엔진 순서 · UC1 A5 · 실패 사유 코드)
CREATE TABLE IF NOT EXISTS engine_attempt (
  request_id      BIGINT        NOT NULL,
  attempt_no      SMALLINT      NOT NULL,
  engine_name     VARCHAR(40)   NOT NULL,
  engine_version  VARCHAR(40)   NOT NULL,
  outcome         VARCHAR(16)   NOT NULL,
  failure_code    VARCHAR(40)   NULL,
  started_at      TIMESTAMP(3)  NOT NULL,
  ended_at        TIMESTAMP(3)  NULL,
  -- [MariaDB] TIMESTAMPDIFF — 행 안에서 계산되는 소요 시간은 생성 컬럼으로 둔다
  duration_ms     BIGINT GENERATED ALWAYS AS (TIMESTAMPDIFF(MICROSECOND, started_at, ended_at) DIV 1000) STORED,
  -- BR-ENG-02: 성공은 요청당 한 번(성공하면 다음 엔진을 부르지 않는다)
  success_marker  SMALLINT GENERATED ALWAYS AS (CASE WHEN outcome = 'success' THEN 1 ELSE NULL END) STORED,
  CONSTRAINT pk_engine_attempt PRIMARY KEY (request_id, attempt_no),
  CONSTRAINT uq_engine_one_success UNIQUE (request_id, success_marker),
  CONSTRAINT fk_attempt_job FOREIGN KEY (request_id) REFERENCES processing_job (request_id),
  CONSTRAINT chk_attempt_no CHECK (attempt_no >= 1),
  CONSTRAINT chk_attempt_outcome CHECK (outcome IN ('success','error','timeout','stopped','no_notes','convert_failed')),
  CONSTRAINT chk_attempt_failure CHECK ((outcome = 'success' AND failure_code IS NULL)
                                     OR (outcome <> 'success' AND failure_code IS NOT NULL)),
  CONSTRAINT chk_attempt_time CHECK (ended_at IS NULL OR ended_at >= started_at)
);

-- B3 타당성 점검 항목별 값 (BR-FBK-07 · BR-OPS-03 "등급과 점검 항목별 값")
CREATE TABLE IF NOT EXISTS validity_check_item (
  request_id      BIGINT         NOT NULL,
  item_code       VARCHAR(20)    NOT NULL,
  measured_value  DECIMAL(12,4)  NOT NULL,
  CONSTRAINT pk_validity_item PRIMARY KEY (request_id, item_code),
  CONSTRAINT fk_validity_job FOREIGN KEY (request_id) REFERENCES processing_job (request_id),
  CONSTRAINT chk_validity_item CHECK (item_code IN ('note_count','beat_sum','range_leap',
                                                    'yulmyeong_ratio','engine_confidence'))
);

-- B4 단계별 소요 시간 (BR-OPS-03 · SC-004) — 엔진·추천·렌더링 시간은 각자 테이블에 있으므로 여기 두지 않는다
CREATE TABLE IF NOT EXISTS stage_timing (
  request_id   BIGINT        NOT NULL,
  stage_code   VARCHAR(12)   NOT NULL,
  started_at   TIMESTAMP(3)  NOT NULL,
  ended_at     TIMESTAMP(3)  NULL,
  duration_ms  BIGINT GENERATED ALWAYS AS (TIMESTAMPDIFF(MICROSECOND, started_at, ended_at) DIV 1000) STORED,
  CONSTRAINT pk_stage_timing PRIMARY KEY (request_id, stage_code),
  CONSTRAINT fk_stage_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT chk_stage_code CHECK (stage_code IN ('check','queue','structure','jg_convert','validity')),
  CONSTRAINT chk_stage_time CHECK (ended_at IS NULL OR ended_at >= started_at)
);


-- =====================================================================
-- 영역 C. 결과물 (쓰기 주체: 웹 서비스 · 모델 API 서버(렌더링) · 생애: 24시간)
-- =====================================================================

-- C2 결과 악보 원본 (H1 · 편집해도 바뀌지 않는다 · BR-EDT-04)
CREATE TABLE IF NOT EXISTS score_result (
  result_id             BIGINT        NOT NULL AUTO_INCREMENT,
  request_id            BIGINT        NOT NULL,
  origin                VARCHAR(10)   NOT NULL,
  musicxml_uri          VARCHAR(500)  NULL,
  midi_uri              VARCHAR(500)  NULL,
  fallback_template_id  BIGINT        NULL,
  original_ensemble_id  BIGINT        NULL,   -- 원래 악기 정보(BR-PLY-04)
  created_at            TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at            TIMESTAMP(3)  NULL,
  CONSTRAINT pk_score_result PRIMARY KEY (result_id),
  -- 요청마다 출처별 결과는 하나. 사용자 요청 대체(UC2 A1)는 인식 결과 옆에 대체 결과를 더한다
  CONSTRAINT uq_result_origin UNIQUE (request_id, origin),
  CONSTRAINT uq_result_request UNIQUE (result_id, request_id),   -- 합성 FK 대상
  CONSTRAINT fk_result_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT fk_result_template FOREIGN KEY (fallback_template_id) REFERENCES fallback_template (template_id),
  CONSTRAINT fk_result_original FOREIGN KEY (original_ensemble_id) REFERENCES ensemble (ensemble_id),
  CONSTRAINT chk_result_origin CHECK (origin IN ('recognized','direct','fallback')),
  -- BR-FBK-01: 대체 결과는 템플릿에서 나온다
  CONSTRAINT chk_result_template CHECK ((origin = 'fallback' AND fallback_template_id IS NOT NULL)
                                     OR (origin <> 'fallback' AND fallback_template_id IS NULL)),
  -- BR-PLY-04: 원래 악기 정보는 직행(MIDI·MusicXML) 결과에만 있다
  CONSTRAINT chk_result_original CHECK (original_ensemble_id IS NULL OR origin = 'direct'),
  -- BR-RET-01: 지우기 전에는 두 파일 위치가 모두 있고, 지운 뒤에는 없다
  CONSTRAINT chk_result_deleted CHECK ((deleted_at IS NULL AND musicxml_uri IS NOT NULL AND midi_uri IS NOT NULL)
                                    OR (deleted_at IS NOT NULL AND musicxml_uri IS NULL AND midi_uri IS NULL))
);


-- =====================================================================
-- 영역 D. 듣기·편집·음원 (쓰기 주체: 웹 서비스(사용자 조작) · 추천 모델 · 생애: 세션 또는 24시간)
-- =====================================================================

-- D4 추천 (2.2~2.4 · 5.8 · BR-REC-01 · UC5 사후조건 ③)
CREATE TABLE IF NOT EXISTS recommendation (
  recommendation_id  BIGINT         NOT NULL AUTO_INCREMENT,
  request_id         BIGINT         NOT NULL,
  requested_at       TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  responded_at       TIMESTAMP(3)   NULL,
  outcome            VARCHAR(16)    NOT NULL,
  model_name         VARCHAR(40)    NULL,     -- 규칙표 또는 scikit-learn 분류기
  model_version      VARCHAR(40)    NULL,
  feature_tempo      VARCHAR(20)    NULL,     -- 빠르기 (C4 "빠르기 느림")
  feature_mode       VARCHAR(20)    NULL,     -- 선법 (C4 "계면조")
  feature_range      VARCHAR(40)    NULL,     -- 음역
  feature_density    DECIMAL(8,3)   NULL,     -- 음표 밀도
  duration_ms        BIGINT GENERATED ALWAYS AS (TIMESTAMPDIFF(MICROSECOND, requested_at, responded_at) DIV 1000) STORED,
  CONSTRAINT pk_recommendation PRIMARY KEY (recommendation_id),
  CONSTRAINT fk_recommendation_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT chk_rec_outcome CHECK (outcome IN ('pending','ok','model_failed','no_response','api_down','feature_failed')),
  -- BR-ENG-01·04: 추천을 받았으면 모델 이름·버전이 있다
  CONSTRAINT chk_rec_model CHECK (outcome <> 'ok' OR (model_name IS NOT NULL AND model_version IS NOT NULL)),
  CONSTRAINT chk_rec_time CHECK (responded_at IS NULL OR responded_at >= requested_at)
);

-- D5 추천 조합 선택지
CREATE TABLE IF NOT EXISTS recommendation_option (
  recommendation_id  BIGINT    NOT NULL,
  rank_no            SMALLINT  NOT NULL,
  ensemble_id        BIGINT    NOT NULL,
  CONSTRAINT pk_recommendation_option PRIMARY KEY (recommendation_id, rank_no),
  CONSTRAINT fk_option_recommendation FOREIGN KEY (recommendation_id)
    REFERENCES recommendation (recommendation_id) ON DELETE CASCADE,
  CONSTRAINT fk_option_ensemble FOREIGN KEY (ensemble_id) REFERENCES ensemble (ensemble_id),
  CONSTRAINT chk_option_rank CHECK (rank_no >= 1)
);

-- D6 연주 악기 구성 선택 (UC5 사후조건 ② · 2.5 · 5.9 · Key Entities "선택하거나 추천된 악기 구성")
CREATE TABLE IF NOT EXISTS instrument_selection (
  selection_id  BIGINT        NOT NULL AUTO_INCREMENT,
  request_id    BIGINT        NOT NULL,
  ensemble_id   BIGINT        NOT NULL,
  source        VARCHAR(16)   NOT NULL,
  selected_at   TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_instrument_selection PRIMARY KEY (selection_id),
  CONSTRAINT fk_selection_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT fk_selection_ensemble FOREIGN KEY (ensemble_id) REFERENCES ensemble (ensemble_id),
  -- 처음 기본값 · 사용자 선택 · API 선택 항목 적용 · 원본으로 되돌리기
  CONSTRAINT chk_selection_source CHECK (source IN ('initial_default','user_choice','api_option','revert_default'))
);

-- D7 사용자 음원 .sf2 (Key Entities 사용자 커스텀 악기 · H3 · G8 · BR-SF2-01~04)
CREATE TABLE IF NOT EXISTS user_soundfont (
  soundfont_id         BIGINT        NOT NULL AUTO_INCREMENT,
  session_id           CHAR(36)      NOT NULL,
  file_name            VARCHAR(255)  NOT NULL,
  size_bytes           BIGINT        NOT NULL,
  storage_uri          VARCHAR(500)  NULL,
  uploaded_at          TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  api_copy_uri         VARCHAR(500)  NULL,     -- MP3 렌더링용으로 모델 API 서버에 보낸 사본(UC8 A3)
  api_copy_sent_at     TIMESTAMP(3)  NULL,
  file_deleted_at      TIMESTAMP(3)  NULL,
  api_copy_deleted_at  TIMESTAMP(3)  NULL,
  CONSTRAINT pk_user_soundfont PRIMARY KEY (soundfont_id),
  CONSTRAINT fk_soundfont_session FOREIGN KEY (session_id) REFERENCES anon_session (session_id),
  -- G8 · BR-SF2-01: 확장자 .sf2, 50MB(52428800 바이트) 이하
  CONSTRAINT chk_g8_extension CHECK (LOWER(file_name) LIKE '%.sf2'),
  CONSTRAINT chk_g8_size CHECK (size_bytes > 0 AND size_bytes <= 52428800),
  -- BR-SF2-03: 파일을 지웠으면 위치가 없다
  CONSTRAINT chk_soundfont_deleted CHECK ((file_deleted_at IS NULL AND storage_uri IS NOT NULL)
                                       OR (file_deleted_at IS NOT NULL AND storage_uri IS NULL)),
  -- BR-SF2-04: 사본은 보낸 적이 있어야 지울 수 있다
  CONSTRAINT chk_soundfont_copy CHECK ((api_copy_uri IS NULL) = (api_copy_sent_at IS NULL)
                                    AND (api_copy_deleted_at IS NULL OR api_copy_sent_at IS NOT NULL))
);

-- D8 편집본 (H2 · SD_01 §5-3 "원본과 편집본을 별도 엔티티로") — 자동 저장본은 사용자 기기에 있고 DB 밖이다
CREATE TABLE IF NOT EXISTS edited_score (
  edit_id              BIGINT        NOT NULL AUTO_INCREMENT,
  request_id           BIGINT        NOT NULL,
  base_result_id       BIGINT        NOT NULL,   -- 편집이 딛고 선 원본(덮어쓰지 않는다)
  musicxml_uri         VARCHAR(500)  NULL,       -- 편집 반영 MusicXML(서버 사본)
  transpose_semitones  SMALLINT      NOT NULL DEFAULT 0,
  first_edited_at      TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_changed_at      TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  reverted_at          TIMESTAMP(3)  NULL,       -- 마지막 [원본으로 되돌리기]
  finished_at          TIMESTAMP(3)  NULL,       -- 편집 마치기(2.12)
  deleted_at           TIMESTAMP(3)  NULL,
  CONSTRAINT pk_edited_score PRIMARY KEY (edit_id),
  CONSTRAINT uq_edited_one_per_request UNIQUE (request_id),
  CONSTRAINT uq_edited_request UNIQUE (edit_id, request_id),   -- 합성 FK 대상
  -- BR-EDT-04 · H1: 원본은 같은 요청의 결과여야 한다(합성 FK)
  CONSTRAINT fk_edited_base FOREIGN KEY (base_result_id, request_id) REFERENCES score_result (result_id, request_id),
  CONSTRAINT chk_edited_deleted CHECK (deleted_at IS NULL OR musicxml_uri IS NULL)
);

-- D9 편집본 트랙 (BR-EDT-07 · 2.7 · 2.9 · UC8 4단계)
CREATE TABLE IF NOT EXISTS edited_track (
  edit_id        BIGINT       NOT NULL,
  track_no       SMALLINT     NOT NULL,
  part_origin    VARCHAR(12)  NOT NULL,   -- 원래 성부 / 원래 선율 복사
  instrument_id  BIGINT       NOT NULL,   -- 서비스 악기. .sf2 를 지정했으면 "지정 전 악기"(BR-RND-04·07)
  soundfont_id   BIGINT       NULL,       -- 사용자 음원 지정. 세션이 끝나 지워지면 NULL(서비스 악기로 돌아감)
  volume_level   SMALLINT     NULL,
  CONSTRAINT pk_edited_track PRIMARY KEY (edit_id, track_no),
  CONSTRAINT fk_track_edit FOREIGN KEY (edit_id) REFERENCES edited_score (edit_id) ON DELETE CASCADE,
  CONSTRAINT fk_track_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (instrument_id),
  CONSTRAINT fk_track_soundfont FOREIGN KEY (soundfont_id) REFERENCES user_soundfont (soundfont_id) ON DELETE SET NULL,
  CONSTRAINT chk_track_no CHECK (track_no >= 1),
  -- BR-EDT-07: 추가 트랙은 원래 선율을 복사한 성부다
  CONSTRAINT chk_track_origin CHECK (part_origin IN ('original','melody_copy')),
  CONSTRAINT chk_track_volume CHECK (volume_level >= 0)
);

-- C3 형식별 결과물 (UC7 사후조건 ②③ · BR-RND-01~07 · C6)
CREATE TABLE IF NOT EXISTS derived_file (
  file_id              BIGINT        NOT NULL AUTO_INCREMENT,
  request_id           BIGINT        NOT NULL,
  format               VARCHAR(8)    NOT NULL,
  basis                VARCHAR(8)    NOT NULL,   -- 원본 / 편집본
  edit_id              BIGINT        NULL,
  ensemble_id          BIGINT        NULL,       -- MP3 를 만든 연주 악기 구성(만든 순간 고정)
  render_status        VARCHAR(10)   NOT NULL,
  renderer_name        VARCHAR(40)   NULL,
  renderer_version     VARCHAR(40)   NULL,
  requested_at         TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  render_started_at    TIMESTAMP(3)  NULL,
  render_finished_at   TIMESTAMP(3)  NULL,
  failure_reason       VARCHAR(60)   NULL,
  storage_uri          VARCHAR(500)  NULL,
  deleted_at           TIMESTAMP(3)  NULL,
  render_ms            BIGINT GENERATED ALWAYS AS
                         (TIMESTAMPDIFF(MICROSECOND, render_started_at, render_finished_at) DIV 1000) STORED,
  CONSTRAINT pk_derived_file PRIMARY KEY (file_id),
  CONSTRAINT uq_derived_request UNIQUE (file_id, request_id),   -- 합성 FK 대상
  CONSTRAINT fk_derived_request FOREIGN KEY (request_id) REFERENCES score_request (request_id),
  CONSTRAINT fk_derived_edit FOREIGN KEY (edit_id, request_id) REFERENCES edited_score (edit_id, request_id),
  CONSTRAINT fk_derived_ensemble FOREIGN KEY (ensemble_id) REFERENCES ensemble (ensemble_id),
  CONSTRAINT chk_derived_format CHECK (format IN ('mp3','pdf','midi','musicxml')),
  CONSTRAINT chk_derived_basis CHECK ((basis = 'edited' AND edit_id IS NOT NULL)
                                   OR (basis = 'original' AND edit_id IS NULL)),
  CONSTRAINT chk_derived_status CHECK (render_status IN ('queued','rendering','ready','failed')),
  -- BR-RND-04·07: MIDI·MusicXML 은 렌더러·대기열을 거치지 않고 바로 준비된다
  CONSTRAINT chk_derived_direct_formats CHECK (format IN ('mp3','pdf')
                                            OR (render_status = 'ready' AND renderer_name IS NULL
                                                AND render_started_at IS NULL)),
  -- BR-RND-05: 준비된 MP3·PDF 에는 렌더러 이름·버전이 있다
  CONSTRAINT chk_derived_renderer CHECK (format NOT IN ('mp3','pdf') OR render_status <> 'ready'
                                      OR (renderer_name IS NOT NULL AND renderer_version IS NOT NULL
                                          AND render_finished_at IS NOT NULL)),
  -- BR-RND-02: 실패에는 이유가 있다(다시 시도 안내의 근거)
  CONSTRAINT chk_derived_failure CHECK ((render_status = 'failed') = (failure_reason IS NOT NULL)),
  -- 준비됨이고 지우지 않았으면 위치가 있다(BR-RET-01)
  CONSTRAINT chk_derived_uri CHECK ((render_status = 'ready' AND deleted_at IS NULL) = (storage_uri IS NOT NULL))
);

-- C4 내려받기 기록 (BR-EDT-05 형식별 내려받기 여부 · 1.17 · 3.7)
CREATE TABLE IF NOT EXISTS download_event (
  download_id     BIGINT        NOT NULL AUTO_INCREMENT,
  request_id      BIGINT        NOT NULL,
  format          VARCHAR(8)    NOT NULL,
  result_id       BIGINT        NULL,   -- 편집 전 결과(S1 의 MusicXML·MIDI)
  file_id         BIGINT        NULL,   -- 형식별 결과물(S3)
  downloaded_at   TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_download_event PRIMARY KEY (download_id),
  CONSTRAINT fk_download_result FOREIGN KEY (result_id, request_id) REFERENCES score_result (result_id, request_id),
  CONSTRAINT fk_download_file FOREIGN KEY (file_id, request_id) REFERENCES derived_file (file_id, request_id),
  CONSTRAINT chk_download_format CHECK (format IN ('mp3','pdf','midi','musicxml')),
  CONSTRAINT chk_download_one_source CHECK ((result_id IS NOT NULL AND file_id IS NULL)
                                         OR (result_id IS NULL AND file_id IS NOT NULL)),
  -- FR-022: 편집 전 결과로는 MusicXML·MIDI 만 받는다
  CONSTRAINT chk_download_result_format CHECK (result_id IS NULL OR format IN ('midi','musicxml'))
);


-- =====================================================================
-- 영역 E (계속). API 명세 확인본 (쓰기 주체: 웹 서비스가 health·versions 조회 · 생애: 마지막 확인본 유지)
-- =====================================================================

-- E4 API 서버 확인본 (4.1 · 6.6 · UC11 E1~E3 · UC9 A3)
CREATE TABLE IF NOT EXISTS api_spec_snapshot (
  snapshot_id          BIGINT        NOT NULL AUTO_INCREMENT,
  checked_at           TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  health_status        VARCHAR(12)   NOT NULL,
  api_version          VARCHAR(20)   NULL,
  mismatch_with_menu   BOOLEAN       NULL,   -- 메뉴에 저장된 목록과 서버 명세가 달랐는지(UC11 E1)
  CONSTRAINT pk_api_spec_snapshot PRIMARY KEY (snapshot_id),
  CONSTRAINT chk_snapshot_health CHECK (health_status IN ('ok','stopped','unreachable')),
  CONSTRAINT chk_snapshot_version CHECK (health_status <> 'ok' OR api_version IS NOT NULL)
);

-- E5 엔드포인트 (Key Entities API 엔드포인트 · BR-API-01·02)
CREATE TABLE IF NOT EXISTS api_endpoint (
  snapshot_id      BIGINT         NOT NULL,
  http_method      VARCHAR(8)     NOT NULL,
  path             VARCHAR(100)   NOT NULL,
  feature_name     VARCHAR(100)   NOT NULL,
  input_format     VARCHAR(500)   NOT NULL,
  response_format  VARCHAR(500)   NOT NULL,
  example_text     VARCHAR(2000)  NULL,     -- 접근 키 자리는 비운 예시(UC11 5단계)
  engine_name      VARCHAR(40)    NULL,
  CONSTRAINT pk_api_endpoint PRIMARY KEY (snapshot_id, http_method, path),
  CONSTRAINT fk_endpoint_snapshot FOREIGN KEY (snapshot_id) REFERENCES api_spec_snapshot (snapshot_id) ON DELETE CASCADE,
  CONSTRAINT chk_endpoint_method CHECK (http_method IN ('GET','POST'))
);

-- E6 확인본의 엔진 버전 (S6 서버 상태 줄 "엔진 버전: 마지막 확인")
CREATE TABLE IF NOT EXISTS snapshot_engine_version (
  snapshot_id     BIGINT       NOT NULL,
  engine_name     VARCHAR(40)  NOT NULL,
  engine_version  VARCHAR(40)  NOT NULL,
  CONSTRAINT pk_snapshot_engine PRIMARY KEY (snapshot_id, engine_name),
  CONSTRAINT fk_snapshot_engine FOREIGN KEY (snapshot_id) REFERENCES api_spec_snapshot (snapshot_id) ON DELETE CASCADE
);


-- =====================================================================
-- 영역 F (계속). 변경 이력 · 평가셋
-- =====================================================================

-- F5 운영자 조치 이력 (BR-OPS-08 · FR-052) — 설정 변경분은 판본 차이로 계산하므로(v_setting_change_history) 여기 두지 않는다
CREATE TABLE IF NOT EXISTS change_history (
  history_id    BIGINT        NOT NULL AUTO_INCREMENT,
  operator_id   BIGINT        NOT NULL,
  changed_at    TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  target_type   VARCHAR(16)   NOT NULL,
  target_ref    VARCHAR(40)   NOT NULL,   -- 다형 참조(대상 표에 따라 뜻이 다르다) — 점검 쿼리 참고
  field_name    VARCHAR(40)   NOT NULL,
  before_value  VARCHAR(500)  NULL,
  after_value   VARCHAR(500)  NULL,
  CONSTRAINT pk_change_history PRIMARY KEY (history_id),
  CONSTRAINT fk_history_operator FOREIGN KEY (operator_id) REFERENCES operator_account (operator_id),
  CONSTRAINT chk_history_target CHECK (target_type IN ('access_key','key_application','license_policy')),
  CONSTRAINT chk_history_field CHECK (field_name IN ('issued','status','call_limit_per_day','retained','confirmed'))
);

-- F6 평가셋 항목 (Key Entities 평가셋 · 가짜 악보 묶음 · SC-012·016·017)
CREATE TABLE IF NOT EXISTS eval_item (
  item_id        BIGINT        NOT NULL AUTO_INCREMENT,
  set_kind       VARCHAR(6)    NOT NULL,     -- 진짜 악보 15종 / 가짜 악보 묶음
  sheet_kind     VARCHAR(12)   NULL,         -- 진짜 악보의 종류
  fake_label     VARCHAR(40)   NULL,         -- 공책·원고지·표·글자 문서·블라인드·풍경·백지·빈 오선지
  file_uri       VARCHAR(500)  NOT NULL,
  registered_at  TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_eval_item PRIMARY KEY (item_id),
  CONSTRAINT chk_eval_set CHECK (set_kind IN ('real','fake')),
  CONSTRAINT chk_eval_kind CHECK ((set_kind = 'real' AND sheet_kind IS NOT NULL
                                    AND sheet_kind IN ('jeongganbo','staff','handwritten') AND fake_label IS NULL)
                               OR (set_kind = 'fake' AND sheet_kind IS NULL AND fake_label IS NOT NULL))
);

-- F7 평가셋 실행 결과 — 평가도 보통 요청으로 흘려 같은 판정을 받는다(요청 기록을 참조)
CREATE TABLE IF NOT EXISTS eval_run_result (
  run_id      BIGINT        NOT NULL AUTO_INCREMENT,
  item_id     BIGINT        NOT NULL,
  request_id  BIGINT        NOT NULL,
  run_at      TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT pk_eval_run_result PRIMARY KEY (run_id),
  CONSTRAINT uq_eval_run_request UNIQUE (request_id),
  CONSTRAINT fk_eval_run_item FOREIGN KEY (item_id) REFERENCES eval_item (item_id),
  CONSTRAINT fk_eval_run_request FOREIGN KEY (request_id) REFERENCES score_request (request_id)
);


-- =====================================================================
-- 영역 G. 공통 추적 (쓰기 주체: 게이트를 판정한 모든 구성요소 · 생애: 영구, 보관 기간 미정)
-- =====================================================================

-- G1 게이트 이벤트 (게이트를 1급 엔티티로 — 발생과 해제를 이력으로)
CREATE TABLE IF NOT EXISTS gate_event (
  event_id        BIGINT        NOT NULL AUTO_INCREMENT,
  gate_code       VARCHAR(3)    NOT NULL,
  occurred_at     TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  channel         VARCHAR(5)    NOT NULL,
  subject_type    VARCHAR(16)   NOT NULL,
  subject_ref     VARCHAR(64)   NULL,     -- 다형 참조 — 점검 쿼리 참고
  reason_code     VARCHAR(40)   NOT NULL,
  released_at     TIMESTAMP(3)  NULL,
  release_action  VARCHAR(40)   NULL,
  CONSTRAINT pk_gate_event PRIMARY KEY (event_id),
  -- G9 는 "키 원문 컬럼이 없음"으로 구조상 막으므로 이벤트가 없다
  CONSTRAINT chk_gate_code CHECK (gate_code IN ('G1','G2','G3','G4','G5','G6','G7','G8','G10','G11')),
  CONSTRAINT chk_gate_channel CHECK (channel IN ('web','api','admin')),
  CONSTRAINT chk_gate_subject CHECK (subject_type IN ('session','access_key','api_call','request','operator',
                                                      'soundfont','setting_version','client')),
  CONSTRAINT chk_gate_release CHECK ((released_at IS NULL AND release_action IS NULL)
                                  OR (released_at IS NOT NULL AND release_action IS NOT NULL
                                      AND released_at >= occurred_at))
);


-- =====================================================================
-- 인덱스 — FK 인덱스는 InnoDB 가 만든다. 여기에는 조회 경로용만 둔다
-- =====================================================================
CREATE INDEX IF NOT EXISTS ix_request_received     ON score_request (received_at);            -- G4 · P0 삭제 대상
CREATE INDEX IF NOT EXISTS ix_request_channel_kind ON score_request (channel, file_kind, route); -- S6 지표
CREATE INDEX IF NOT EXISTS ix_request_status       ON score_request (status);                 -- 동시 처리 수(G3)
CREATE INDEX IF NOT EXISTS ix_call_key_time        ON api_call_log (access_key_id, called_at); -- G3 호출 한도
CREATE INDEX IF NOT EXISTS ix_application_email    ON key_application (contact_email, applied_at);   -- G11
CREATE INDEX IF NOT EXISTS ix_application_address  ON key_application (client_address, applied_at);  -- G11
CREATE INDEX IF NOT EXISTS ix_application_applied  ON key_application (applied_at);           -- 7일 삭제
CREATE INDEX IF NOT EXISTS ix_soundfont_session    ON user_soundfont (session_id, file_deleted_at);  -- G8 3개
CREATE INDEX IF NOT EXISTS ix_derived_queue        ON derived_file (render_status, requested_at);    -- 대기 순서
CREATE INDEX IF NOT EXISTS ix_selection_request    ON instrument_selection (request_id, selected_at);
CREATE INDEX IF NOT EXISTS ix_gate_code_time       ON gate_event (gate_code, occurred_at);
CREATE INDEX IF NOT EXISTS ix_setting_created      ON processing_setting_version (created_at);


-- =====================================================================
-- 뷰 — 유도 속성과 게이트 판정의 단일 지점
-- =====================================================================

-- 지금 설정 = 마지막으로 저장한 판본 (H5)
CREATE OR REPLACE VIEW v_current_setting AS
SELECT s.*
  FROM processing_setting_version s
 WHERE s.setting_version_id = (SELECT MAX(setting_version_id) FROM processing_setting_version);

-- S1 처리 중 "대기" 순서 (BR-OPS-01 · UC1 A1)
CREATE OR REPLACE VIEW v_request_queue_position AS
SELECT r.request_id,
       (SELECT COUNT(*) FROM score_request q
         WHERE q.status = 'queued' AND q.received_at <= r.received_at) AS queue_position
  FROM score_request r
 WHERE r.status = 'queued';

-- G8 세션당 사용자 음원 3개 — 단일 판정 지점(BR-SF2-02). S2 [음원 올리기] 비활성과 트리거가 함께 읽는다
CREATE OR REPLACE VIEW v_session_soundfont_count AS
SELECT s.session_id,
       (SELECT COUNT(*) FROM user_soundfont f
         WHERE f.session_id = s.session_id AND f.file_deleted_at IS NULL) AS active_count,
       CASE WHEN (SELECT COUNT(*) FROM user_soundfont f
                   WHERE f.session_id = s.session_id AND f.file_deleted_at IS NULL) >= 3
            THEN 0 ELSE 1 END                                             AS can_upload
  FROM anon_session s;

-- G11 신청 빈도 제한 — 단일 판정 지점(FR-061 · UC15 E2). "다시 신청할 수 있는 시각"도 여기서 낸다
--   같은 연락 이메일 또는 같은 접속 주소 기준. 값이 미정(NULL)이면 행이 없어 제한하지 않는다
CREATE OR REPLACE VIEW v_apply_rate_window AS
SELECT x.rate_key,
       COUNT(*)                                                           AS recent_count,
       s.apply_rate_limit_count                                           AS limit_count,
       MIN(x.applied_at) + INTERVAL s.apply_rate_window_minutes MINUTE    AS next_allowed_at,
       CASE WHEN COUNT(*) >= s.apply_rate_limit_count THEN 1 ELSE 0 END   AS is_blocked
  FROM (SELECT CONCAT('email:', a.contact_email)  AS rate_key, a.applied_at FROM key_application a
        UNION ALL
        SELECT CONCAT('addr:', a.client_address) AS rate_key, a.applied_at FROM key_application a) x
  CROSS JOIN v_current_setting s
 WHERE s.apply_rate_limit_count IS NOT NULL
   AND s.apply_rate_window_minutes IS NOT NULL
   AND x.applied_at > CURRENT_TIMESTAMP(3) - INTERVAL s.apply_rate_window_minutes MINUTE
 GROUP BY x.rate_key, s.apply_rate_limit_count, s.apply_rate_window_minutes;

-- 서버 상태 = 마지막 확인본 (S4-A 레일 "서버 상태" · S6 서버 상태 줄 · UC11 E2·E3 · UC9 A3·E4)
CREATE OR REPLACE VIEW v_server_status AS
SELECT p.snapshot_id, p.checked_at, p.health_status, p.api_version, p.mismatch_with_menu,
       (SELECT MAX(o.snapshot_id) FROM api_spec_snapshot o WHERE o.health_status = 'ok') AS last_ok_snapshot_id
  FROM api_spec_snapshot p
 WHERE p.snapshot_id = (SELECT MAX(snapshot_id) FROM api_spec_snapshot);

-- 엔드포인트 목록 = 마지막으로 정상 확인한 명세(서버가 멈춰도 "마지막 확인본"을 보인다, UC11 E2)
CREATE OR REPLACE VIEW v_endpoint_menu AS
SELECT e.*
  FROM api_endpoint e
 WHERE e.snapshot_id = (SELECT MAX(o.snapshot_id) FROM api_spec_snapshot o WHERE o.health_status = 'ok');

-- S4-B 발급된 키 목록 — 신청 내용이 7일 뒤 지워졌는지(UC14 E6 "이미 삭제된 신청")
CREATE OR REPLACE VIEW v_key_admin_list AS
SELECT k.key_id, k.key_kind, k.key_prefix, k.call_limit_per_day, k.issued_at, k.status, k.application_no,
       CASE WHEN k.key_kind = 'external' AND a.key_id IS NULL THEN 1 ELSE 0 END AS application_purged
  FROM access_key k
  LEFT JOIN key_application a ON a.key_id = k.key_id;

-- G4 보관 기간 — 단일 판정 지점 (BR-RET-01 24시간). 화면·API·트리거·P0 가 모두 이 뷰를 읽는다
CREATE OR REPLACE VIEW v_request_retention AS
SELECT r.request_id,
       r.request_no,
       r.received_at,
       r.received_at + INTERVAL '24' HOUR                                        AS expires_at,
       GREATEST(0, TIMESTAMPDIFF(SECOND, CURRENT_TIMESTAMP(3), r.received_at + INTERVAL '24' HOUR))
                                                                                 AS remaining_seconds,
       CASE WHEN r.purged_at IS NOT NULL
              OR CURRENT_TIMESTAMP(3) >= r.received_at + INTERVAL '24' HOUR
            THEN 1 ELSE 0 END                                                    AS is_expired
  FROM score_request r;

-- P0 삭제 대상 (0.1): 만료되었지만 아직 지우지 않은 요청
CREATE OR REPLACE VIEW v_purge_due_requests AS
SELECT v.request_id, v.request_no, v.expires_at
  FROM v_request_retention v
  JOIN score_request r ON r.request_id = v.request_id
 WHERE r.purged_at IS NULL
   AND CURRENT_TIMESTAMP(3) >= v.expires_at;

-- 처리 단계 표시 (C1 처리 단계 · UC13 6단계 상태 값) — 웹과 API 의 낱말을 한 곳에서 정한다
CREATE OR REPLACE VIEW v_request_stage_label AS
SELECT r.request_id,
       r.channel,
       CASE
         WHEN r.status = 'received'             THEN '접수'
         WHEN r.status = 'queued'               THEN '대기'
         WHEN r.status = 'converting'           THEN '변환 중'
         WHEN r.status = 'awaiting_type_answer' THEN '종류 확인'
         WHEN r.status = 'rendering'            THEN '연주 생성'
         WHEN r.status = 'service_down'         THEN '서비스 중단'
         WHEN r.route = 'fallback'              THEN CASE WHEN r.channel = 'api' THEN '대체 완료' ELSE '대체' END
         ELSE '완료'
       END AS stage_label,
       CASE
         WHEN r.status <> 'completed'  THEN NULL
         WHEN r.route = 'fallback'     THEN '대체 결과로 완료'
         WHEN r.route = 'direct'       THEN '직행 결과로 완료'
         ELSE '완료'
       END AS completion_label,
       -- C3 결과 상태 띠: 신뢰 · 주의 · 대체 · 직행
       CASE
         WHEN r.status <> 'completed' THEN NULL
         WHEN r.route = 'fallback'    THEN 'fallback'
         WHEN r.route = 'direct'      THEN 'direct'
         WHEN j.validity_grade = 'caution' THEN 'caution'
         ELSE 'trust'
       END AS result_band
  FROM score_request r
  LEFT JOIN processing_job j ON j.request_id = r.request_id;

-- 지금 결과 = 적용 경로에 맞는 출처의 결과 (UC2 A1: 사용자 요청 대체 뒤에는 대체 결과)
CREATE OR REPLACE VIEW v_current_result AS
SELECT sr.*
  FROM score_result sr
  JOIN score_request r ON r.request_id = sr.request_id
 WHERE sr.origin = CASE r.route WHEN 'recognize' THEN 'recognized'
                                WHEN 'direct'    THEN 'direct'
                                ELSE 'fallback' END;

-- 요청의 엔진 이름·버전 = 성공한 시도 (BR-ENG-01·04)
CREATE OR REPLACE VIEW v_job_engine AS
SELECT a.request_id, a.engine_name, a.engine_version
  FROM engine_attempt a
 WHERE a.outcome = 'success';

-- 요청 기록 (S6 요청 기록 탭 · 6.4 · H4 · BR-OPS-03)
CREATE OR REPLACE VIEW v_request_log AS
SELECT r.request_id, r.request_no, r.channel, r.route, r.status, r.fallback_reason,
       r.file_kind, r.chosen_score_type,
       j.confirmed_score_type, j.structure_verdict, j.type_mismatch, j.type_answer, j.validity_grade,
       e.engine_name, e.engine_version,
       (SELECT duration_ms FROM stage_timing t WHERE t.request_id = r.request_id AND t.stage_code = 'check')      AS check_ms,
       (SELECT duration_ms FROM stage_timing t WHERE t.request_id = r.request_id AND t.stage_code = 'queue')      AS queue_ms,
       (SELECT duration_ms FROM stage_timing t WHERE t.request_id = r.request_id AND t.stage_code = 'structure')  AS structure_ms,
       (SELECT SUM(a.duration_ms) FROM engine_attempt a WHERE a.request_id = r.request_id)                       AS recognize_ms,
       (SELECT duration_ms FROM stage_timing t WHERE t.request_id = r.request_id AND t.stage_code = 'jg_convert') AS jg_convert_ms,
       (SELECT duration_ms FROM stage_timing t WHERE t.request_id = r.request_id AND t.stage_code = 'validity')   AS validity_ms,
       (SELECT MAX(c.duration_ms) FROM recommendation c WHERE c.request_id = r.request_id)                      AS recommend_ms,
       (SELECT MAX(d.render_ms) FROM derived_file d WHERE d.request_id = r.request_id)                          AS render_ms,
       r.received_at, r.completed_at
  FROM score_request r
  LEFT JOIN processing_job j ON j.request_id = r.request_id
  LEFT JOIN v_job_engine e   ON e.request_id = r.request_id;

-- SC-004: 기록이 빠진 요청 (S6 "기록이 빠진 요청 N건")
CREATE OR REPLACE VIEW v_missing_log AS
SELECT r.request_id, r.request_no, r.channel,
       CASE WHEN NOT EXISTS (SELECT 1 FROM stage_timing t WHERE t.request_id = r.request_id AND t.stage_code = 'check')
            THEN 1 ELSE 0 END AS missing_stage_timing,
       CASE WHEN r.route = 'recognize' AND NOT EXISTS (SELECT 1 FROM v_job_engine e WHERE e.request_id = r.request_id)
            THEN 1 ELSE 0 END AS missing_engine_version,
       CASE WHEN r.route = 'recognize' AND NOT EXISTS
                 (SELECT 1 FROM processing_job j WHERE j.request_id = r.request_id AND j.validity_grade IS NOT NULL)
            THEN 1 ELSE 0 END AS missing_grade
  FROM score_request r
 WHERE r.status = 'completed'
   AND (NOT EXISTS (SELECT 1 FROM stage_timing t WHERE t.request_id = r.request_id AND t.stage_code = 'check')
        OR (r.route = 'recognize' AND NOT EXISTS (SELECT 1 FROM v_job_engine e WHERE e.request_id = r.request_id))
        OR (r.route = 'recognize' AND NOT EXISTS
            (SELECT 1 FROM processing_job j WHERE j.request_id = r.request_id AND j.validity_grade IS NOT NULL)));

-- S6 지표 5종 (BR-OPS-04 계산식 · BR-OPS-05 전체와 웹/API별) — 목표값이 없어 기준선 값만 낸다
CREATE OR REPLACE VIEW v_metric_by_channel AS
SELECT scope,
       SUM(is_image)                                                        AS image_requests,
       SUM(is_first_pass)                                                   AS first_pass_trust,
       CASE WHEN SUM(is_image) = 0 THEN NULL ELSE SUM(is_first_pass) / SUM(is_image) END AS first_pass_rate,
       SUM(is_caution)                                                      AS caution_count,
       CASE WHEN SUM(is_image) = 0 THEN NULL ELSE SUM(is_fallback) / SUM(is_image) END   AS fallback_rate,
       CASE WHEN SUM(has_result) = 0 THEN NULL ELSE SUM(is_edited) / SUM(has_result) END AS edit_usage_rate,
       MAX(wait_ms)                                                         AS max_wait_ms,
       SUM(is_down)                                                         AS service_down_count
  FROM (
    SELECT sc.scope, x.*
      FROM (SELECT 'all' AS scope UNION ALL SELECT 'web' UNION ALL SELECT 'api') sc
      JOIN (
        SELECT r.channel,
               CASE WHEN r.file_kind = 'image' THEN 1 ELSE 0 END AS is_image,
               CASE WHEN r.file_kind = 'image' AND r.route = 'recognize' AND j.validity_grade = 'trust'
                         AND r.status = 'completed'
                         AND (r.channel = 'api' OR r.first_played_at IS NOT NULL) THEN 1 ELSE 0 END AS is_first_pass,
               CASE WHEN r.route = 'recognize' AND j.validity_grade = 'caution' THEN 1 ELSE 0 END AS is_caution,
               CASE WHEN r.file_kind = 'image' AND r.route = 'fallback' THEN 1 ELSE 0 END AS is_fallback,
               CASE WHEN r.status = 'completed' THEN 1 ELSE 0 END AS has_result,
               CASE WHEN EXISTS (SELECT 1 FROM edited_score es WHERE es.request_id = r.request_id) THEN 1 ELSE 0 END AS is_edited,
               CASE WHEN r.channel = 'web' THEN TIMESTAMPDIFF(MICROSECOND, r.received_at, r.first_played_at) DIV 1000
                    ELSE TIMESTAMPDIFF(MICROSECOND, r.received_at, r.completed_at) DIV 1000 END AS wait_ms,
               CASE WHEN r.status = 'service_down' THEN 1 ELSE 0 END AS is_down
          FROM score_request r
          LEFT JOIN processing_job j ON j.request_id = r.request_id
      ) x ON sc.scope = 'all' OR sc.scope = x.channel
  ) m
 GROUP BY scope;

-- S6 대체 이유별 (6.3 · BR-FBK-03)
CREATE OR REPLACE VIEW v_fallback_by_reason AS
SELECT r.channel, r.fallback_reason, COUNT(*) AS cnt
  FROM score_request r
 WHERE r.route = 'fallback'
 GROUP BY r.channel, r.fallback_reason;

-- G2 접근 키 — 단일 판정 지점 (BR-API-03 · BR-KEY-02)
CREATE OR REPLACE VIEW v_key_validity AS
SELECT k.key_id, k.key_hash, k.key_kind,
       CASE WHEN k.status = 'active' THEN 1 ELSE 0 END AS is_valid
  FROM access_key k;

-- G3 호출 한도 — 단일 판정 지점 (BR-API-04 · BR-KEY-03). "하루"의 경계(시간대)는 미정: 여기서는 DB 날짜
--   [MariaDB] CAST(... AS TIMESTAMP) 미지원 — DATE 와 TIMESTAMP 비교는 자정 기준으로 암묵 변환된다
CREATE OR REPLACE VIEW v_key_quota AS
SELECT q.key_id, q.call_limit_per_day, q.calls_today,
       q.call_limit_per_day - q.calls_today                 AS remaining_today,
       CASE WHEN q.call_limit_per_day IS NOT NULL AND q.calls_today >= q.call_limit_per_day
            THEN 1 ELSE 0 END                               AS is_exhausted
  FROM (SELECT k.key_id, k.call_limit_per_day,
               (SELECT COUNT(*) FROM api_call_log c
                 WHERE c.access_key_id = k.key_id AND c.outcome = 'accepted'
                   AND c.called_at >= CURRENT_DATE) AS calls_today
          FROM access_key k) q;

-- G3 동시 처리 수 (BR-OPS-01 · BR-API-04)
CREATE OR REPLACE VIEW v_active_processing AS
SELECT COUNT(*) AS active_count
  FROM score_request r
 WHERE r.status IN ('converting','rendering');

-- G7 · BR-RND-03: 라이선스 확인 여부 — 웹 MP3 "팀 내부 시연용" 표시와 API MP3 제외가 같은 값을 읽는다
CREATE OR REPLACE VIEW v_mp3_license AS
SELECT p.confirmed                                   AS license_confirmed,
       CASE WHEN p.confirmed THEN 0 ELSE 1 END       AS web_mp3_internal_only,
       CASE WHEN p.confirmed THEN 1 ELSE 0 END       AS api_mp3_allowed
  FROM license_policy p
 WHERE p.policy_code = 'sound_and_renderer';

-- BR-KEY-06: 신청 내용 7일 보관 — "삭제 예정" 열과 P0 삭제가 같은 식을 읽는다
CREATE OR REPLACE VIEW v_application_retention AS
SELECT a.key_id,
       a.applied_at,
       a.applied_at + INTERVAL '7' DAY                    AS delete_due_at,
       CASE WHEN a.retained_at IS NOT NULL THEN 1 ELSE 0 END AS is_retained,
       CASE WHEN a.retained_at IS NULL AND CURRENT_TIMESTAMP(3) >= a.applied_at + INTERVAL '7' DAY
            THEN 1 ELSE 0 END                             AS is_purge_due
  FROM key_application a;

-- S4-B 신청 목록 — 마스킹 뷰(이름·이메일 가림). 가리지 않은 값을 보일지는 미정(미해결)
CREATE OR REPLACE VIEW v_key_application_masked AS
SELECT k.application_no,
       CONCAT(SUBSTRING(a.applicant_name, 1, 1), '**')                                   AS applicant_name_masked,
       a.affiliation,
       CONCAT(SUBSTRING(a.contact_email, 1, 1), '***@',
              SUBSTRING(a.contact_email, POSITION('@' IN a.contact_email) + 1))           AS contact_email_masked,
       a.purpose, a.applied_at, v.delete_due_at, v.is_retained,
       k.key_prefix, k.status AS key_status
  FROM key_application a
  JOIN access_key k             ON k.key_id = a.key_id
  JOIN v_application_retention v ON v.key_id = a.key_id;

-- C7 관리자 머리띠 "운영자 kim**"
CREATE OR REPLACE VIEW v_operator_masked AS
SELECT o.operator_id, CONCAT(SUBSTRING(o.login_id, 1, 3), '**') AS login_id_masked, o.disabled_at
  FROM operator_account o;

-- C4 악기 고르기 목록 순서 (BR-PLY-03 국악기 먼저)
CREATE OR REPLACE VIEW v_instrument_menu AS
SELECT i.instrument_id, i.name, i.family,
       CASE i.family WHEN 'gugak' THEN 1 ELSE 2 END AS menu_group
  FROM instrument i
 WHERE i.is_active = TRUE;

-- 지금 연주 악기 구성 = 요청의 마지막 선택 (C5 "지금 연주")
CREATE OR REPLACE VIEW v_current_selection AS
SELECT s.request_id, s.ensemble_id, s.source, s.selected_at
  FROM instrument_selection s
 WHERE s.selection_id = (SELECT MAX(s2.selection_id) FROM instrument_selection s2 WHERE s2.request_id = s.request_id);

-- C6 "대기 N번째" — 렌더링 대기 순서
CREATE OR REPLACE VIEW v_render_queue_position AS
SELECT d.file_id, d.request_id, d.format,
       (SELECT COUNT(*) FROM derived_file q
         WHERE q.render_status = 'queued' AND q.requested_at <= d.requested_at) AS queue_position
  FROM derived_file d
 WHERE d.render_status = 'queued';

-- C6 형식별 현재 상태 = 요청·형식·기준별 마지막 시도 (다시 시도는 새 행)
CREATE OR REPLACE VIEW v_current_derived_file AS
SELECT d.*
  FROM derived_file d
 WHERE d.file_id = (SELECT MAX(d2.file_id) FROM derived_file d2
                     WHERE d2.request_id = d.request_id AND d2.format = d.format AND d2.basis = d.basis);

-- BR-EDT-05 편집 기록 (편집 여부 · 값 · 형식별 편집 뒤 내려받기 여부)
CREATE OR REPLACE VIEW v_edit_record AS
SELECT r.request_id,
       CASE WHEN es.edit_id IS NULL THEN 0 ELSE 1 END AS edited,
       es.transpose_semitones,
       (SELECT COUNT(*) FROM edited_track t WHERE t.edit_id = es.edit_id)                         AS track_count,
       (SELECT COUNT(*) FROM edited_track t WHERE t.edit_id = es.edit_id AND t.soundfont_id IS NOT NULL) AS soundfont_tracks,
       MAX(CASE WHEN d.format = 'mp3'      THEN 1 ELSE 0 END) AS downloaded_mp3_after_edit,
       MAX(CASE WHEN d.format = 'pdf'      THEN 1 ELSE 0 END) AS downloaded_pdf_after_edit,
       MAX(CASE WHEN d.format = 'midi'     THEN 1 ELSE 0 END) AS downloaded_midi_after_edit,
       MAX(CASE WHEN d.format = 'musicxml' THEN 1 ELSE 0 END) AS downloaded_musicxml_after_edit
  FROM score_request r
  LEFT JOIN edited_score es ON es.request_id = r.request_id
  LEFT JOIN (SELECT de.request_id, de.format
               FROM download_event de
               JOIN derived_file f ON f.file_id = de.file_id
              WHERE f.basis = 'edited') d ON d.request_id = r.request_id
 GROUP BY r.request_id, es.edit_id, es.transpose_semitones;

-- P0 0.4·0.5: 세션이 끝났는데 남은 사용자 음원(SC-006 위반 후보)
CREATE OR REPLACE VIEW v_purge_due_soundfonts AS
SELECT f.soundfont_id, f.session_id,
       CASE WHEN f.file_deleted_at IS NULL THEN 1 ELSE 0 END                             AS file_pending,
       CASE WHEN f.api_copy_sent_at IS NOT NULL AND f.api_copy_deleted_at IS NULL THEN 1 ELSE 0 END AS api_copy_pending
  FROM user_soundfont f
  JOIN anon_session s ON s.session_id = f.session_id
 WHERE s.ended_at IS NOT NULL
   AND (f.file_deleted_at IS NULL OR (f.api_copy_sent_at IS NOT NULL AND f.api_copy_deleted_at IS NULL));

-- 설정 변경 이력(BR-OPS-08) = 연속한 판본의 차이. 저장하지 않고 계산한다
--   [MariaDB] GROUP_CONCAT — 표준 LISTAGG 미지원(이탈 D1)
CREATE OR REPLACE VIEW v_setting_change_history AS
WITH v AS (
  SELECT s.*,
         (SELECT GROUP_CONCAT(o.engine_name ORDER BY o.seq SEPARATOR '>') FROM setting_engine_order o
           WHERE o.setting_version_id = s.setting_version_id AND o.score_type = 'staff')      AS staff_order,
         (SELECT GROUP_CONCAT(o.engine_name ORDER BY o.seq SEPARATOR '>') FROM setting_engine_order o
           WHERE o.setting_version_id = s.setting_version_id AND o.score_type = 'jeongganbo') AS jeongganbo_order,
         LAG(s.setting_version_id) OVER (ORDER BY s.setting_version_id) AS prev_id
    FROM processing_setting_version s
), pair AS (
  SELECT cur.setting_version_id, cur.created_by, cur.created_at,
         cur.staff_order AS c_staff, prv.staff_order AS p_staff,
         cur.jeongganbo_order AS c_jg, prv.jeongganbo_order AS p_jg,
         cur.timeout_seconds AS c_timeout, prv.timeout_seconds AS p_timeout,
         cur.max_concurrency AS c_conc, prv.max_concurrency AS p_conc,
         cur.fallback_enabled AS c_fb, prv.fallback_enabled AS p_fb,
         cur.default_call_limit_per_day AS c_lim, prv.default_call_limit_per_day AS p_lim,
         cur.apply_rate_limit_count AS c_rc, prv.apply_rate_limit_count AS p_rc,
         cur.apply_rate_window_minutes AS c_rw, prv.apply_rate_window_minutes AS p_rw,
         cur.structure_threshold AS c_st, prv.structure_threshold AS p_st,
         cur.grade_caution_boundary AS c_gc, prv.grade_caution_boundary AS p_gc,
         cur.grade_distrust_boundary AS c_gd, prv.grade_distrust_boundary AS p_gd
    FROM v cur LEFT JOIN v prv ON prv.setting_version_id = cur.prev_id
)
SELECT setting_version_id, created_by AS operator_id, created_at AS changed_at, field_name,
       before_value, after_value
  FROM (
    SELECT setting_version_id, created_by, created_at, 'staff_engine_order' AS field_name, p_staff AS before_value, c_staff AS after_value FROM pair WHERE NOT (c_staff <=> p_staff)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'jeongganbo_engine_order', p_jg, c_jg FROM pair WHERE NOT (c_jg <=> p_jg)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'timeout_seconds', CAST(p_timeout AS CHAR), CAST(c_timeout AS CHAR) FROM pair WHERE NOT (c_timeout <=> p_timeout)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'max_concurrency', CAST(p_conc AS CHAR), CAST(c_conc AS CHAR) FROM pair WHERE NOT (c_conc <=> p_conc)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'fallback_enabled', CAST(p_fb AS CHAR), CAST(c_fb AS CHAR) FROM pair WHERE NOT (c_fb <=> p_fb)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'default_call_limit_per_day', CAST(p_lim AS CHAR), CAST(c_lim AS CHAR) FROM pair WHERE NOT (c_lim <=> p_lim)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'apply_rate_limit_count', CAST(p_rc AS CHAR), CAST(c_rc AS CHAR) FROM pair WHERE NOT (c_rc <=> p_rc)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'apply_rate_window_minutes', CAST(p_rw AS CHAR), CAST(c_rw AS CHAR) FROM pair WHERE NOT (c_rw <=> p_rw)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'structure_threshold', CAST(p_st AS CHAR), CAST(c_st AS CHAR) FROM pair WHERE NOT (c_st <=> p_st)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'grade_caution_boundary', CAST(p_gc AS CHAR), CAST(c_gc AS CHAR) FROM pair WHERE NOT (c_gc <=> p_gc)
    UNION ALL SELECT setting_version_id, created_by, created_at, 'grade_distrust_boundary', CAST(p_gd AS CHAR), CAST(c_gd AS CHAR) FROM pair WHERE NOT (c_gd <=> p_gd)
  ) diff;
-- [MariaDB] <=> 는 NULL 안전 비교다. 표준은 IS NOT DISTINCT FROM.

-- 변경 이력 탭 전체 = 설정 판본 차이 + 운영자 조치
CREATE OR REPLACE VIEW v_change_history_all AS
SELECT 'setting' AS target_type, CAST(setting_version_id AS CHAR) AS target_ref, operator_id, changed_at,
       field_name, before_value, after_value
  FROM v_setting_change_history
UNION ALL
SELECT target_type, target_ref, operator_id, changed_at, field_name, before_value, after_value
  FROM change_history;

-- S6 평가셋 탭 (SC-012 · SC-016 · SC-017)
CREATE OR REPLACE VIEW v_eval_metrics AS
SELECT
  -- SC-012 정간보 진짜 악보 중 정상 변환(대체가 아님) 비율
  (SELECT CASE WHEN COUNT(*) = 0 THEN NULL ELSE SUM(CASE WHEN r.route = 'recognize' THEN 1 ELSE 0 END) / COUNT(*) END
     FROM eval_run_result x JOIN eval_item i ON i.item_id = x.item_id JOIN score_request r ON r.request_id = x.request_id
    WHERE i.set_kind = 'real' AND i.sheet_kind = 'jeongganbo')                            AS jeongganbo_normal_rate,
  -- SC-016 가짜 악보가 "신뢰"로 나간 건수(목표 0)
  (SELECT COUNT(*)
     FROM eval_run_result x JOIN eval_item i ON i.item_id = x.item_id
     JOIN processing_job j ON j.request_id = x.request_id
    WHERE i.set_kind = 'fake' AND j.validity_grade = 'trust')                             AS fake_passed_as_trust,
  -- SC-016 가짜 악보 중 구조 확인에서 걸러진 비율
  (SELECT CASE WHEN COUNT(*) = 0 THEN NULL ELSE SUM(CASE WHEN r.fallback_reason = 'no_structure' THEN 1 ELSE 0 END) / COUNT(*) END
     FROM eval_run_result x JOIN eval_item i ON i.item_id = x.item_id JOIN score_request r ON r.request_id = x.request_id
    WHERE i.set_kind = 'fake')                                                            AS fake_structure_filter_rate,
  -- SC-017 진짜 악보 중 구조 없음·불신으로 잘못 막힌 비율
  (SELECT CASE WHEN COUNT(*) = 0 THEN NULL
               ELSE SUM(CASE WHEN r.fallback_reason IN ('no_structure','distrust') THEN 1 ELSE 0 END) / COUNT(*) END
     FROM eval_run_result x JOIN eval_item i ON i.item_id = x.item_id JOIN score_request r ON r.request_id = x.request_id
    WHERE i.set_kind = 'real')                                                            AS real_false_block_rate;


-- =====================================================================
-- 트리거 — CHECK 로 표현할 수 없는 규칙(시점 의존 · 다중 행 · 다른 테이블 참조)
-- =====================================================================
DELIMITER //

-- G11 신청 빈도 제한 (UC15 E2 · FR-061 · BR-KEY-07) — 판정은 v_apply_rate_window 한 곳.
--   값이 미정(NULL)이면 제한하지 않는다. 거절 이벤트(gate_event)는 롤백되므로 앱이 따로 쓴다.
CREATE OR REPLACE TRIGGER trg_g11_application_rate
BEFORE INSERT ON key_application
FOR EACH ROW
BEGIN
  IF EXISTS (SELECT 1 FROM v_apply_rate_window w
              WHERE w.rate_key IN (CONCAT('email:', NEW.contact_email), CONCAT('addr:', NEW.client_address))
                AND w.is_blocked = 1) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'G11: application rate limit exceeded';
  END IF;
END//

-- G8 세션당 사용자 음원 3개 (BR-SF2-02 · UC8 E3) — 다중 행 조건. 판정은 v_session_soundfont_count 한 곳
CREATE OR REPLACE TRIGGER trg_g8_soundfont_count
BEFORE INSERT ON user_soundfont
FOR EACH ROW
BEGIN
  IF (SELECT can_upload FROM v_session_soundfont_count WHERE session_id = NEW.session_id) = 0 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'G8: max 3 soundfonts per session';
  END IF;
END//

-- 결과 악보 원본 넣기 규칙 — 다른 테이블 참조
--   BR-FBK-02·06: 대체 결과의 템플릿은 요청 경로의 보유처(웹 요청=웹 템플릿, API 요청=API 서버 템플릿)
--   UC2 E4·E5: 시간 초과·엔진 중단으로 이미 대체된 요청에 늦게 온 인식 결과는 받지 않는다
CREATE OR REPLACE TRIGGER trg_score_result_insert
BEFORE INSERT ON score_result
FOR EACH ROW
BEGIN
  DECLARE v_channel VARCHAR(4);
  DECLARE v_route VARCHAR(10);
  DECLARE v_reason VARCHAR(20);
  DECLARE v_holder VARCHAR(12);
  SELECT channel, route, fallback_reason INTO v_channel, v_route, v_reason
    FROM score_request WHERE request_id = NEW.request_id;
  IF NEW.origin = 'fallback' THEN
    SELECT holder INTO v_holder FROM fallback_template WHERE template_id = NEW.fallback_template_id;
    IF (v_channel = 'web' AND v_holder <> 'web') OR (v_channel = 'api' AND v_holder <> 'api_server') THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'BR-FBK-02: template holder must match request channel';
    END IF;
  END IF;
  IF NEW.origin = 'recognized' AND v_route = 'fallback' AND v_reason IN ('timeout','engine_stopped') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'UC2-E4: late recognition result ignored';
  END IF;
END//

-- G4 보관 기간 — 만료된 요청으로 결과물을 만들거나 내려받지 못한다(판정은 v_request_retention 한 곳)
CREATE OR REPLACE TRIGGER trg_g4_derived_file
BEFORE INSERT ON derived_file
FOR EACH ROW
BEGIN
  IF (SELECT is_expired FROM v_request_retention WHERE request_id = NEW.request_id) = 1 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'G4: retention period expired';
  END IF;
END//

CREATE OR REPLACE TRIGGER trg_g4_download
BEFORE INSERT ON download_event
FOR EACH ROW
BEGIN
  IF (SELECT is_expired FROM v_request_retention WHERE request_id = NEW.request_id) = 1 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'G4: retention period expired';
  END IF;
END//

-- 요청 상태 머신 — 완료·서비스 중단은 끝 상태다(BR-FBK-04). 완료 뒤 사용자 요청 대체(UC2 A1)는 경로만 바뀐다
CREATE OR REPLACE TRIGGER trg_request_terminal
BEFORE UPDATE ON score_request
FOR EACH ROW
BEGIN
  IF OLD.status IN ('completed','service_down') AND NEW.status <> OLD.status THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'request status is terminal';
  END IF;
  IF OLD.status = 'completed' AND OLD.route <> NEW.route
     AND NOT (NEW.route = 'fallback' AND NEW.fallback_reason = 'user_request') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'only user_request fallback may change a completed route';
  END IF;
END//

DELIMITER ;
